title: UFCity
logo: "/assets/img/ufcity-logo.png"
# show_downloads: true
description: >
  <b>Building smart cities smartly</b>
  <h>
  <br><br>
  <center>
  <a href="http://www.ufc.br"> <img src="/ufcity/assets/img/ufc.jpg"> </a> 
  <a href="http://www.mdcc.ufc.br"> <img src="/ufcity/assets/img/mdcc.png"> </a> 
  <a href="http://www.dc.ufc.br"> <img src="/ufcity/assets/img/computer-department.png"> </a> 
  <a href="http://www.arida.ufc.br"> <img src="/ufcity/assets/img/arida.png"> </a> 
  </center>
  <br><br>
  <p class="view">
    <a href="https://github.com/makleyston-ufc">
      View all repositories on GitHub
      <small>makleyston/</small>
    </a>
  </p>
google_analytics: G-FDH6QE2FWG
theme: jekyll-theme-minimal